version: '3'

services:
  mdbook:
    container_name: mdbook-popos
    image: peaceiris/mdbook:v0.4.15
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - ${PWD}:/docs
    command:
      - serve
      - /docs
      - --hostname
      - '0.0.0.0'
      - --port
      - '3001'